using UnityEngine;
using UnityEngine.UI;
using UnityEngine.Networking;
using System.Collections;
using TMPro;

public class BugReporter : MonoBehaviour
{
    [Header("Configuration")]
    [Tooltip("Create a Webhook in Discord (Channel Settings > Integrations) and paste URL here.")]
    public string discordWebhookURL = "";

    [Header("UI References")]
    public GameObject reportPanel;
    public TMP_InputField userNoteInput;
    public TMP_InputField nameInput; // NEW: Drag your Name input field here
    public Button sendButton;
    public TextMeshProUGUI statusText;

    private bool isSending = false;

    // Toggle this from your Pause Menu button
    public void TogglePanel()
    {
        if (reportPanel == null) return;
        bool isActive = !reportPanel.activeSelf;
        reportPanel.SetActive(isActive);

        if (isActive)
        {
            // Ensure it renders on top of everything else (like the Pause Menu)
            reportPanel.transform.SetAsLastSibling();

            // Pause if opening
            if (GameManager.Instance) Time.timeScale = 0f;
            if (userNoteInput) userNoteInput.Select();
        }
        else
        {
            // Unpause if closing (ONLY if we were playing).
            if (GameManager.Instance && GameManager.Instance.currentState == GameManager.GameState.Playing)
                Time.timeScale = 1f;
        }
    }

    public void SendReport()
    {
        if (isSending) return;
        if (string.IsNullOrEmpty(discordWebhookURL))
        {
            if (statusText) statusText.text = "Setup Error: No Webhook URL.";
            return;
        }

        StartCoroutine(SendToDiscordEmbed());
    }

    IEnumerator SendToDiscordEmbed()
    {
        isSending = true;
        if (sendButton) sendButton.interactable = false;
        if (statusText) statusText.text = "Sending Report...";

        // 1. GATHER DATA
        string userNote = userNoteInput.text;
        if (string.IsNullOrWhiteSpace(userNote)) userNote = "No details provided.";

        // NEW: Get Reporter Name
        string reporterName = "Anonymous";
        if (nameInput != null && !string.IsNullOrWhiteSpace(nameInput.text))
        {
            reporterName = nameInput.text;
        }

        string sceneName = UnityEngine.SceneManagement.SceneManager.GetActiveScene().name;

        // NEW: Get Device Name for context
        string deviceName = SystemInfo.deviceName;

        string debugInfo = "N/A";
        if (GameManager.Instance)
        {
            debugInfo = GameManager.Instance.GetDebugInfo();
        }

        // Clean up strings for JSON
        string cleanNote = EscapeJson(userNote);
        string cleanDebug = EscapeJson(debugInfo);
        string cleanReporter = EscapeJson(reporterName);
        string cleanDevice = EscapeJson(deviceName);

        // 2. CONSTRUCT JSON PAYLOAD (Discord Embed Format)
        string jsonPayload = $@"
        {{
            ""username"": ""Bug Bot"",
            ""embeds"": [
                {{
                    ""title"": ""Bug Report"",
                    ""color"": 16711680,
                    ""fields"": [
                        {{
                            ""name"": ""Reporter"",
                            ""value"": ""{cleanReporter}"",
                            ""inline"": true
                        }},
                        {{
                            ""name"": ""Scene"",
                            ""value"": ""{sceneName}"",
                            ""inline"": true
                        }},
                        {{
                            ""name"": ""User Note"",
                            ""value"": ""{cleanNote}"",
                            ""inline"": false
                        }},
                        {{
                            ""name"": ""System"",
                            ""value"": ""{Application.platform} | {cleanDevice}"",
                            ""inline"": false
                        }},
                        {{
                            ""name"": ""Game State"",
                            ""value"": ""```{cleanDebug}```"",
                            ""inline"": false
                        }}
                    ],
                    ""footer"": {{
                        ""text"": ""Generated by Unity BugReporter""
                    }}
                }}
            ]
        }}";

        // 3. SEND REQUEST
        using (UnityWebRequest www = new UnityWebRequest(discordWebhookURL, "POST"))
        {
            byte[] bodyRaw = System.Text.Encoding.UTF8.GetBytes(jsonPayload);
            www.uploadHandler = new UploadHandlerRaw(bodyRaw);
            www.downloadHandler = new DownloadHandlerBuffer();
            www.SetRequestHeader("Content-Type", "application/json");

            yield return www.SendWebRequest();

            if (www.result == UnityWebRequest.Result.Success)
            {
                if (statusText) statusText.text = "Report Sent!";
                Debug.Log("Discord Webhook sent successfully.");
                yield return new WaitForSeconds(1.5f);
                TogglePanel(); // Close UI
                if (userNoteInput) userNoteInput.text = "";
                // We typically keep the name filled in for convenience
            }
            else
            {
                if (statusText) statusText.text = "Failed to Send.";
                Debug.LogError($"Webhook Error: {www.error}\nResponse: {www.downloadHandler.text}");
            }
        }

        if (sendButton) sendButton.interactable = true;
        isSending = false;
    }

    // Helper to prevent JSON breaking on quotes or newlines
    private string EscapeJson(string s)
    {
        if (string.IsNullOrEmpty(s)) return "";
        return s
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "");
    }
}